### ISSUE TITLE
ajax无刷新下拉文章列表时Markdown渲染问题

### ISSUE THREAD

**Issue by marlonfan** [jiangmuzi/jianshu#1]
当ajax无刷新下拉文章列表的时候,markdown的```代码块并没有着色

**Comment by marlonfan** [comment]
![image](https://cloud.githubusercontent.com/assets/9349370/10862755/261b7f28-7ff1-11e5-80f8-ca4bd046e935.png)

**Comment by qq450192529** [comment]
的时候

**Comment by marlonfan** [comment]
已解决.  在无刷新加载完成以后再用higtlight渲染一次即好.

**Comment by jiangmuzi** [comment]
默认的情况下，列表页加载的只是文档的简介，其中并没有html代码，所以并没有去考虑需要渲染code的情况

**Comment by marlonfan** [comment]
@jiangmuzi 是哦。。。我有小修改。嘿嘿。
